### PR TITLE
Reorganize the code into pkg and internal directories, this moves the oci directory out of stacker binary's way

### LINKED ISSUE #296: stacker clean deletes oci/oci.go
```
piggie@pigpen:~/github/stacker (master) $ git status
On branch master
Your branch is up to date with 'chofnar/master'.

nothing to commit, working tree clean
piggie@pigpen:~/github/stacker (master) $ stacker clean
piggie@pigpen:~/github/stacker (master) $ git status
On branch master
Your branch is up to date with 'chofnar/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    oci/oci.go

no changes added to commit (use "git add" and/or "git commit -a")
```

### LINKED ISSUE #332: Cannot run basic example: Invalid image detected
## Setup
stacker.yaml
```
first:
  from:
    type: docker
    url: docker://centos:latest
```
uid and gid maps:
```
$ cat /etc/subuid
amiculas:100000:65536
$ cat  /etc/subgid
amiculas:100000:65536
```

# Issue
### Running as regular user:
```
$ ./stacker --debug build --layer-type=squashfs
stacker version 52ab507fc074e0b51b9b860eae0f6e36092aa4db
usernsexec-ing [usernsexec u 0 1000 1 1 100001 65535 g 0 1000 1 1 100001 65535 -- /home/amiculas/work/stacker/stacker --internal-userns --debug build --layer-type=squashfs]
stacker version 52ab507fc074e0b51b9b860eae0f6e36092aa4db
initializing stacker recipe: stacker.yaml
substituting $STACKER_ROOTFS_DIR to /home/amiculas/work/stacker/roots
substituting $STACKER_STACKER_DIR to /home/amiculas/work/stacker/.stacker
substituting $STACKER_OCI_DIR to /home/amiculas/work/stacker/oci
stacker build order:
0 build /home/amiculas/work/stacker/stacker.yaml: requires: []
building: 0 /home/amiculas/work/stacker/stacker.yaml
substituting $STACKER_ROOTFS_DIR to /home/amiculas/work/stacker/roots
substituting $STACKER_STACKER_DIR to /home/amiculas/work/stacker/.stacker
substituting $STACKER_OCI_DIR to /home/amiculas/work/stacker/oci
Dependency Order [base a b c]
error: invalid image detected
read oci-layout
github.com/opencontainers/umoci/oci/cas/dir.(*dirEngine).validate
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/oci/cas/dir/dir.go:111
github.com/opencontainers/umoci/oci/cas/dir.Open
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/oci/cas/dir/dir.go:407
github.com/opencontainers/umoci.OpenLayout
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/api.go:30
github.com/project-stacker/stacker.(*Builder).build
        /stacker-tree/build.go:296
github.com/project-stacker/stacker.(*Builder).BuildMultiple
        /stacker-tree/build.go:547
main.doBuild
        /stacker-tree/cmd/build.go:112
github.com/urfave/cli.HandleAction
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
validate
github.com/opencontainers/umoci/oci/cas/dir.Open
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/oci/cas/dir/dir.go:408
github.com/opencontainers/umoci.OpenLayout
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/api.go:30
github.com/project-stacker/stacker.(*Builder).build
        /stacker-tree/build.go:296
github.com/project-stacker/stacker.(*Builder).BuildMultiple
        /stacker-tree/build.go:547
main.doBuild
        /stacker-tree/cmd/build.go:112
github.com/urfave/cli.HandleAction
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
open CAS
github.com/opencontainers/umoci.OpenLayout
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/api.go:32
github.com/project-stacker/stacker.(*Builder).build
        /stacker-tree/build.go:296
github.com/project-stacker/stacker.(*Builder).BuildMultiple
        /stacker-tree/build.go:547
main.doBuild
        /stacker-tree/cmd/build.go:112
github.com/urfave/cli.HandleAction
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
error: exit status 1
github.com/project-stacker/stacker/container.MaybeRunInUserns
        /stacker-tree/container/userns.go:90
main.main.func3
        /stacker-tree/cmd/main.go:298
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:264
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
```
### Running as root:
```
$ sudo ./stacker --debug build
stacker version 52ab507fc074e0b51b9b860eae0f6e36092aa4db
No uid mappings, running as root
stacker version 52ab507fc074e0b51b9b860eae0f6e36092aa4db
initializing stacker recipe: stacker.yaml
substituting $STACKER_ROOTFS_DIR to /home/amiculas/work/stacker/roots
substituting $STACKER_STACKER_DIR to /home/amiculas/work/stacker/.stacker
substituting $STACKER_OCI_DIR to /home/amiculas/work/stacker/oci
stacker build order:
0 build /home/amiculas/work/stacker/stacker.yaml: requires: []
building: 0 /home/amiculas/work/stacker/stacker.yaml
substituting $STACKER_ROOTFS_DIR to /home/amiculas/work/stacker/roots
substituting $STACKER_STACKER_DIR to /home/amiculas/work/stacker/.stacker
substituting $STACKER_OCI_DIR to /home/amiculas/work/stacker/oci
Dependency Order [first]
error: invalid image detected
read oci-layout
github.com/opencontainers/umoci/oci/cas/dir.(*dirEngine).validate
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/oci/cas/dir/dir.go:111
github.com/opencontainers/umoci/oci/cas/dir.Open
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/oci/cas/dir/dir.go:407
github.com/opencontainers/umoci.OpenLayout
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/api.go:30
github.com/project-stacker/stacker.(*Builder).build
        /stacker-tree/build.go:296
github.com/project-stacker/stacker.(*Builder).BuildMultiple
        /stacker-tree/build.go:547
main.doBuild
        /stacker-tree/cmd/build.go:112
github.com/urfave/cli.HandleAction
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
validate
github.com/opencontainers/umoci/oci/cas/dir.Open
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/oci/cas/dir/dir.go:408
github.com/opencontainers/umoci.OpenLayout
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/api.go:30
github.com/project-stacker/stacker.(*Builder).build
        /stacker-tree/build.go:296
github.com/project-stacker/stacker.(*Builder).BuildMultiple
        /stacker-tree/build.go:547
main.doBuild
        /stacker-tree/cmd/build.go:112
github.com/urfave/cli.HandleAction
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
open CAS
github.com/opencontainers/umoci.OpenLayout
        /stacker-tree/.build/gopath/pkg/mod/github.com/opencontainers/umoci@v0.4.8-0.20220412065115-12453f247749/api.go:32
github.com/project-stacker/stacker.(*Builder).build
        /stacker-tree/build.go:296
github.com/project-stacker/stacker.(*Builder).BuildMultiple
        /stacker-tree/build.go:547
main.doBuild
        /stacker-tree/cmd/build.go:112
github.com/urfave/cli.HandleAction
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.Command.Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
error: exit status 1
github.com/project-stacker/stacker/container.MaybeRunInUserns
        /stacker-tree/container/userns.go:26
main.main.func3
        /stacker-tree/cmd/main.go:298
github.com/urfave/cli.(*App).Run
        /stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:264
main.main
        /stacker-tree/cmd/main.go:303
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1594
```

### PR DESCRIPTION
**Pull request by ariel-miculas**
Fixes #296
Fixes #332

Signed-off-by: Ariel Miculas <ariel.miculas@cisco.com>

### CODE REVIEW

**Comment by hallyn** [comment]
I don't know that we can do this.  At least it'll be painful for all the users of that path.  Definitely major version change sort of thing.

**Comment by rchincha** [comment]
Would organize code under pkg/ and internal/ if need be. That is the golang way to do this.

**Comment by ariel-miculas** [comment]
@rchincha what do you think?

File: cmd/stacker/build.go [hunk 1]
```diff
@@ -4,9 +4,9 @@ import (
 	"fmt"
```
Comment (rchincha) [inline cmd/stacker/build.go:4]: Move all these under pkg/build.go ... etc instead of under cmd/stacker/...

Comment (ariel-miculas) [reply cmd/stacker/build.go:4]: I don't quite understand how this would work. `build.go` and the other go files under `cmd/stacker` are part of the package `main`. I've tried moving all the go files except for main.go, but then I cannot import `pkg/stacker` because:
```
cmd/stacker/main.go:23:2: import "stackerbuild.io/stacker/pkg/stacker" is a program, not an importable package
```
Moving all of them under `pkg/stacker` doesn't seem to follow the go project layout, the main application should be under `cmd/stacker`, as described here: https://github.com/golang-standards/project-layout/tree/master/cmd

Comment (rchincha) [reply cmd/stacker/build.go:4]: yes, you have the change the package to "package stacker" on top line

Comment (ariel-miculas) [reply cmd/stacker/build.go:4]: Thanks. So I should leave main.go in cmd/stacker and move the rest of the files under pkg/stacker?

Comment (rchincha) [reply cmd/stacker/build.go:4]: correct, and once files land there, change the "package main" to "package stacker"

Comment (ariel-miculas) [reply cmd/stacker/build.go:4]: I've tried moving these files to `pkg/stacker` and changing `package main` to `package stacker`, but now files in `pkg/stacker` have a dependency on `cmd/stacker/main.go` (e.g. the `config` variable) and I'm not sure I can add `main.go` as a dependency to files in `pkg/stacker`, it definitely doesn't seem right to me.
Could you help me understand the reason why you want to move these files to `pkg/stacker`?

Comment (ariel-miculas) [reply cmd/stacker/build.go:4]: For reference:
```
go build -tags "exclude_graphdriver_btrfs exclude_graphdriver_devicemapper containers_image_openpgp osusergo netgo " -ldflags "-X main.version=v0.30.1-9-g2ca5d76-dirty -X main.lxc_version=5.0.0~git2209-g5a7b9ce67 " -o stacker-dynamic ./cmd/stacker
# stackerbuild.io/stacker/pkg/stacker
pkg/stacker/build.go:94:25: undefined: config
pkg/stacker/build.go:101:25: undefined: shouldShowProgress
pkg/stacker/check.go:21:24: undefined: config
pkg/stacker/check.go:29:9: undefined: config
pkg/stacker/check.go:31:24: undefined: config
pkg/stacker/check.go:33:51: undefined: config
pkg/stacker/chroot.go:41:38: undefined: config
pkg/stacker/chroot.go:66:27: undefined: config
pkg/stacker/chroot.go:94:26: undefined: config
pkg/stacker/chroot.go:100:42: undefined: config
pkg/stacker/chroot.go:100:42: too many errors
make: *** [Makefile:30: stacker-dynamic] Error 2
```

Comment (rchincha) [reply cmd/stacker/build.go:4]: https://github.com/project-stacker/stacker/pull/356
^ try refactor based on this

Comment (ariel-miculas) [reply cmd/stacker/build.go:4]: is it ok now?

**Comment by rchincha** [comment]
@ariel-miculas can you resolve the conflict? you may just have to move that file again.

**Review by hallyn — APPROVED** [review]
Thank you.  I like it.  Much cleaner layout.

It'll still hurt for anyone using the pkg/ stuff right now, but it's worth it.

And, by switching to cmd/stacker/ you've made room for cmd/atomfs :)

**Comment by ariel-miculas** [comment]
This will need to be updated: https://stackerbuild.io/developer_guide/code_structure/

**Comment by rchincha** [comment]
@ariel-miculas can this wait until after https://github.com/project-stacker/stacker/pull/345, this being mostly a re-org PR.

**Comment by ariel-miculas** [comment]
sure

**Review by rchincha — APPROVED** [review]
lgtm
