### PR TITLE
Fix race condition in stacker's squashfuse mount path.

### LINKED ISSUE #428: Bug: race condition in squashfuse mount path - command not found
### stacker version

v1.0.0-rc1

### Describe the bug

I see this problem occasionally when building bootkit and have seen it elsewhere as well.
[here](https://github.com/project-machine/bootkit/actions/runs/4316377353/jobs/7532358700) is a github-actions reproduce.

The problem manifests itself like:
```
2023-03-02T17:01:18.1854206Z preparing image stubby-build-env...
2023-03-02T17:01:18.1987179Z couldn't find AppArmor profile lxc-container-default-cgns
2023-03-02T17:01:18.2097611Z + pkgtool install binutils gcc gnu-efi libc6-dev make tar
2023-03-02T17:01:18.2098345Z /stacker/.stacker-run.sh: 2: pkgtool: not found
2023-03-02T17:01:18.2153865Z error: run commands failed: execute failed: exit status 127
2023-03-02T17:01:18.2233898Z error: exit status 1
2023-03-02T17:01:18.2238643Z make: *** [Makefile:8: build] Error 1
```

the 'not found' file lives in a layer 'minbase'. they look like this:

 - docker://ubuntu:jammy
 - minbase (does an import pkgtool and runs 'pkgtool upgrade' and 'pkgtool install ca-certificates'
 - other layer (stubby-build-env) based on minbase, runs 'pkgtool' as the first thing in its build process.

bootkit builds with 'stacker recursive-build'.
here is an attempt at a stacker.yaml that would reproduce, but I have not tried it. pkgtool could really be any script.

```yaml
minbase:
  build_only: true
  from:
    type: docker
    url: ${{DOCKER_BASE}}ubuntu:jammy
  import:
    - pkgtool
  run: |
    mirror=${{UBUNTU_MIRROR}}

    rel=$(. /etc/os-release && echo "${VERSION_CODENAME}")
    [ -n "$rel" ]

    cp /etc/apt/sources.list /etc/apt/sources.list.dist
    cat > /etc/apt/sources.list <<EOF
    deb [by-hash=force] $mirror ${rel} main universe
    deb [by-hash=force] $mirror ${rel}-updates main universe
    deb [by-hash=force] $mirror ${rel}-security main universe
    EOF

    cp /stacker/pkgtool /usr/local/bin

    #pkgtool upgrade
    #pkgtool install ca-certificates

rootfs:
  from:
    type: built
    tag: minbase
  run: |
    pkgtool install ca-certificates
```

### To reproduce

I see the issue occasionally just using 'make' in https://github.com/project-machine/bootkit.
I have only seen it once or twice on github actions before now.

### Expected behavior

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by smoser**
This protection was present in one of the callers of squashFuse, but not in another.  The change here just to put them inside squashFuse.

Fixes #428.

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/squashfs/squashfs.go [hunk 1]
```diff
@@ -254,10 +262,23 @@ func squashFuse(squashFile, extractDir string) (*exec.Cmd, error) {
 	log.Debugf("Extracting %s -> %s with squashfuse [%s]", squashFile, extractDir, logf)
 	err = cmd.Start()
 	if err != nil {
-		return nilCmd, err
+		return err
+	}
+
+	err = cmd.Process.Release()
```
Comment (hallyn) [inline pkg/squashfs/squashfs.go:268]: It's *probably* ok to do this, but this does mean that the squashfuse process will not be automatically reaped when stacker exits.  At least not by golang.  Presumably stacker has created its own namespace and that will cause it to be reaped anyway.

**Review by hallyn — APPROVED** [review]

File: pkg/squashfs/squashfs.go (hunk 1 above)
Comment (smoser) [reply pkg/squashfs/squashfs.go:268]: ah. ok. so we could allow the caller to do the Release() if they wanted.
and that probably is better.

**Comment by smoser** [comment]
part of the build (test) timed out https://github.com/project-stacker/stacker/actions/runs/4318221259/jobs/7554679260
Is this new?
